### ISSUE TITLE
Enable iptables server at all times

### ISSUE THREAD

**Issue by fujexo** [adfinis/ansible-role-iptables#4]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

The iptables service should be enabled at all times instead of only at installation time.
https://github.com/adfinis-sygroup/ansible-role-iptables/blob/24663373657b00b280da270151d0db8f172421c4/tasks/configuration.yml#L43-L51

**Comment by keachi** [comment]
AFAIK If we change that, the role is no longer idempotent on older Linux versions. There is an issue, that the service status isn't detected properly.
But I'm fine with that.

**Comment by ayekat** [comment]
Fixed in #9. Closing.
